"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import useSWR from "swr";
import { fetcher } from "@/lib/api";

type Member = { video_id: string; title: string | null; channel_title: string | null; video_url: string; thumbnail_url: string | null; current_view_count: number; velocity_per_hour: number; signal_tier: string; similarity_score: number | null; joined_at: string; is_reupload_suspect: boolean; is_same_channel_duplicate: boolean };
type Snapshot = { observed_at: string; observed_views: number; observed_velocity_per_hour: number; trend_score: number; member_count: number; channel_count: number };
type Trend = { label: string; niche: string | null; status: string; trend_score: number; observed_views: number; observed_velocity_per_hour: number; acceleration: number | null; member_count: number; channel_count: number; first_detected_at: string; last_observed_at: string | null; cluster_reason: string | null; members: Member[]; snapshots: Snapshot[] };
const format = new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 });

function LineChart({ snapshots }: { snapshots: Snapshot[] }) {
  if (snapshots.length < 2) return <div className="flex h-48 items-center justify-center text-sm text-text-tertiary">Need at least two observed snapshots to draw the trend line.</div>;
  const values = snapshots.map((item) => item.observed_velocity_per_hour); const max = Math.max(...values, 1); const width = 680; const height = 180;
  const points = values.map((value, index) => `${(index / (values.length - 1)) * width},${height - 18 - (value / max) * (height - 36)}`).join(" ");
  return <div><svg viewBox={`0 0 ${width} ${height}`} className="h-52 w-full" preserveAspectRatio="none"><line x1="0" y1={height - 18} x2={width} y2={height - 18} stroke="rgba(255,255,255,.14)" /><polyline points={points} fill="none" stroke="rgb(var(--neon))" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{points.split(" ").map((point, index) => <circle key={index} cx={point.split(",")[0]} cy={point.split(",")[1]} r="3" fill="rgb(var(--bg-primary))" stroke="rgb(var(--neon))" strokeWidth="2" />)}</svg><div className="flex justify-between text-xs text-text-tertiary"><span>{new Date(snapshots[0].observed_at).toLocaleString("id-ID")}</span><span>{new Date(snapshots.at(-1)!.observed_at).toLocaleString("id-ID")}</span></div></div>;
}

export default function TopicDetailPage() {
  const params = useParams<{ clusterId: string }>();
  const { data, error } = useSWR<Trend>(params.clusterId ? `/api/v1/youtube/trends/${params.clusterId}` : null, fetcher, { refreshInterval: 30_000 });
  if (error) return <div><Link href="/youtube/trends" className="text-sm text-neon">← Back to topics</Link><p className="mt-5 text-red-400">Topic tidak ditemukan atau belum dapat dibaca.</p></div>;
  if (!data) return <p className="text-text-secondary">Memuat evidence cluster...</p>;
  return <div className="mx-auto max-w-7xl"><Link href="/youtube/trends" className="text-sm text-neon">← Back to topics</Link><section className="mt-5 rounded-xl border border-line bg-surface p-6"><div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-neon">{data.status.replace("_", " ")} · observed cluster</p><h1 className="mt-3 text-3xl font-bold">{data.label}</h1><p className="mt-2 text-text-secondary">{data.niche || "Uncategorized"} · {data.member_count} evidence posts from {data.channel_count} independent channels</p>{data.cluster_reason && <p className="mt-4 text-sm text-text-secondary">{data.cluster_reason}</p>}</div><div className="border-l border-line pl-0 lg:pl-6"><p className="text-xs uppercase tracking-[.14em] text-text-tertiary">Observed views</p><p className="mt-1 font-mono text-3xl">{format.format(data.observed_views)}</p><p className="mt-4 text-xs uppercase tracking-[.14em] text-text-tertiary">Observed velocity</p><p className="mt-1 font-mono text-lg text-neon">{format.format(data.observed_velocity_per_hour)}/hr</p><p className="mt-3 text-xs text-text-tertiary">Score {Math.round(data.trend_score)} · acceleration {data.acceleration == null ? "collecting" : data.acceleration.toFixed(2)}</p></div></div></section>
    <section className="mt-5 rounded-xl border border-line bg-surface p-6"><div className="flex items-baseline justify-between"><div><h2 className="font-semibold">Momentum observed over time</h2><p className="mt-1 text-sm text-text-secondary">Aggregated velocity from the evidence posts captured by this system.</p></div><span className="text-xs text-text-tertiary">Not a YouTube-wide total</span></div><div className="mt-5"><LineChart snapshots={data.snapshots} /></div></section>
    <section className="mt-5"><div className="flex items-baseline justify-between"><div><h2 className="text-xl font-semibold">Evidence posts</h2><p className="mt-1 text-sm text-text-secondary">Individual Shorts that support this cluster. Re-upload and same-channel flags remain visible.</p></div><span className="text-sm text-text-tertiary">{data.members.length} posts</span></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.members.map((member) => <a key={member.video_id} href={member.video_url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border border-line bg-surface transition-colors hover:border-line-strong hover:bg-white/[.03]"><div className="aspect-[16/9] bg-bg-secondary">{member.thumbnail_url && <img src={member.thumbnail_url} alt="" className="h-full w-full object-cover" />}</div><div className="p-4"><p className="text-xs font-semibold text-neon">{member.signal_tier} · {member.similarity_score == null ? "evidence" : `${Math.round(member.similarity_score * 100)}% similarity`}</p><h3 className="mt-2 line-clamp-2 font-semibold">{member.title || member.video_id}</h3><p className="mt-1 truncate text-sm text-text-secondary">{member.channel_title || "Unknown channel"}</p><div className="mt-4 flex gap-4 font-mono text-sm"><span>{format.format(member.current_view_count)} views</span><span className="text-neon">{format.format(member.velocity_per_hour)}/hr</span></div>{(member.is_reupload_suspect || member.is_same_channel_duplicate) && <p className="mt-3 text-xs text-warning">{member.is_reupload_suspect ? "Re-upload suspect" : "Same-channel duplicate"}</p>}</div></a>)}</div></section>
  </div>;
}
