"use client";

import useSWR from "swr";
import { fetcher } from "@/lib/api";

type Coverage = { seen?: number; fresh?: number; old?: number; duplicates?: number; sessions?: number; target_shortfall?: number };
type Report = { raw_candidates_seen: number; fresh_accepted: number; fresh_rate_percent: number; duplicates: number; rejected_old: number; errors: Record<string, number>; age_buckets: Record<string, number>; tier_states: Record<string, number>; tier_transitions: Record<string, number>; velocity_samples_by_age: Record<string, number>; relative_scoring: { enabled: boolean; minimum_samples: number }; profiles: { profile: string; coverage_24h: Coverage }[] };

const labels: Record<string, string> = { "0-2h": "0–2 jam", "2-6h": "2–6 jam", "6-12h": "6–12 jam", "12-24h": "12–24 jam" };

export default function ObservationReportPage() {
  const { data, error } = useSWR<Report>("/api/v1/youtube/observation-report", fetcher, { refreshInterval: 30_000 });
  if (error) return <p className="text-red-400">Laporan belum bisa dimuat. Sistem akan mencoba lagi otomatis.</p>;
  if (!data) return <p className="text-text-secondary">Memuat laporan observasi...</p>;
  const cards = [["Raw candidates", data.raw_candidates_seen], ["Fresh accepted", data.fresh_accepted], ["Fresh rate", `${data.fresh_rate_percent}%`], ["Duplicates", data.duplicates]];
  return <main className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-neon">Y-CGC V4</p><h1 className="mt-2 text-4xl font-bold">24-hour observation report</h1><p className="mt-2 text-text-secondary">Rolling evidence window for threshold review and thesis reporting.</p><section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <div key={String(label)} className="rounded-xl border border-line bg-surface p-4 shadow-card"><p className="text-[10px] font-semibold uppercase tracking-wider text-text-tertiary">{label}</p><p className="mt-2 font-mono text-2xl">{value}</p></div>)}</section><section className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-line bg-surface p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-text-tertiary">Fresh age distribution</p><div className="mt-4 space-y-3">{Object.entries(data.age_buckets).map(([bucket, count]) => <div key={bucket} className="flex justify-between border-b border-line pb-2 text-sm"><span>{labels[bucket]}</span><span className="font-mono text-neon">{count}</span></div>)}</div></div><div className="rounded-xl border border-line bg-surface p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-text-tertiary">Signal states observed</p><div className="mt-4 space-y-3">{Object.entries(data.tier_states).map(([state, count]) => <div key={state} className="flex justify-between border-b border-line pb-2 text-sm"><span>{state}</span><span className="font-mono text-neon">{count}</span></div>)}</div></div></section><section className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-line bg-surface p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-text-tertiary">Profile coverage</p><div className="mt-4 space-y-3">{data.profiles.map(({ profile, coverage_24h: coverage }) => <div key={profile} className="flex flex-wrap justify-between gap-2 border-b border-line pb-2 text-sm"><span>{profile}</span><span className="text-text-secondary">{coverage.seen ?? 0} raw · <span className="text-neon">{coverage.fresh ?? 0} fresh</span> · {coverage.duplicates ?? 0} dup</span></div>)}</div></div><div className="rounded-xl border border-line bg-surface p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-text-tertiary">Relative scoring baseline</p><p className="mt-3 text-sm text-text-secondary">{data.relative_scoring.enabled ? "Active" : "Collecting only"}; requires {data.relative_scoring.minimum_samples} samples per age bucket before activation.</p><div className="mt-4 space-y-3">{Object.entries(data.velocity_samples_by_age).map(([bucket, count]) => <div key={bucket} className="flex justify-between border-b border-line pb-2 text-sm"><span>{labels[bucket]}</span><span className="font-mono">{count} samples</span></div>)}</div></div></section></main>;
}
