const demoItems = [
  { id: "demo-1", niche: "Comedy", title: "Wait until the cat sees the mirror", channel: "Tiny Moments", views: "184K", velocity: "22.4K/hr", fact: "A ginger cat is centered in frame; large yellow text appears at the top.", color: "from-amber-500 via-orange-600 to-rose-700" },
  { id: "demo-2", niche: "Food", title: "The crispiest street-food sound", channel: "Night Market Bites", views: "96K", velocity: "14.8K/hr", fact: "Steam rises from a frying pan and white captions sit over a dark background.", color: "from-red-700 via-orange-500 to-amber-300" },
  { id: "demo-3", niche: "Gaming", title: "One impossible final-second save", channel: "Clutch Replay", views: "251K", velocity: "31.2K/hr", fact: "A blue game arena fills the frame with a bright score indicator in the upper corner.", color: "from-blue-700 via-indigo-700 to-fuchsia-700" },
];

export default function YoutubeDemoPage() {
  return <main className="mx-auto min-h-screen max-w-7xl px-6 py-12"><div className="rounded-xl border border-amber-400/40 bg-amber-400/10 px-4 py-3 text-sm text-amber-200">Demo/Test Data — halaman ini hanya preview desain. Tidak membaca atau menulis data pipeline asli.</div><div className="mt-9"><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-400">Y-CGC V4 Preview</p><h1 className="mt-2 text-4xl font-bold">YouTube Early Breakouts</h1><p className="mt-2 text-zinc-400">Contoh tampilan card ketika breakout nyata berhasil lolos semua tahap.</p></div><section className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{demoItems.map((item) => <article key={item.id} className="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900"><div className={`flex aspect-video items-end bg-gradient-to-br p-4 ${item.color}`}><span className="rounded bg-black/50 px-2 py-1 text-xs font-semibold text-white">Peak frame preview</span></div><div className="p-4"><p className="text-xs font-medium text-cyan-400">{item.niche}</p><h2 className="mt-1 text-lg font-semibold">{item.title}</h2><p className="mt-1 text-sm text-zinc-400">{item.channel}</p><div className="mt-4 flex gap-4 text-sm"><span>{item.views} views</span><span className="text-emerald-400">{item.velocity}</span></div><p className="mt-4 border-t border-zinc-800 pt-3 text-sm leading-6 text-zinc-400">{item.fact}</p></div></article>)}</section><a href="/youtube" className="mt-10 inline-block text-sm text-cyan-400 underline">Back to live dashboard</a></main>;
}
